### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh --verbose build

### ISSUE THREAD

**Issue by laurocesar** [klausbetz/apple-identity-provider-keycloak#45]
I've got this error when building a docker imagem using Keycloak 22.0.1 and Apple Identity Provider Keycloak plugin 1.7.0:

```
ERROR: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh --verbose build
```

Here my Dockerfile:

```Dockerfile
FROM quay.io/keycloak/keycloak:22.0.1 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
ENV KC_HTTP_RELATIVE_PATH="/auth"

# Install custom providers

# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.7.0/apple-identity-provider-1.7.0.jar /opt/keycloak/providers/apple-identity-provider-1.7.0.jar

# build optimized image
RUN /opt/keycloak/bin/kc.sh --verbose build 

FROM quay.io/keycloak/keycloak:22.0.1

COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

And the error when running  `docker build -t my-keycloak:latest .`

```
1.064 2023-07-24 19:19:22,102 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[/ runtime=true resources=null] to QuarkusClassLoader Deployment Class Loader: PROD
1.064 
1.066 ERROR: Failed to run 'build' command.
1.066 Error details:
1.066 java.lang.reflect.InvocationTargetException
1.066 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1.066 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
1.066 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
1.066 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
1.066 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
1.066 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
1.066 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
1.066 	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:81)
1.066 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
1.066 	at picocli.CommandLine.access$1500(CommandLine.java:148)
1.066 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
1.066 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
1.066 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
1.066 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
1.066 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
1.066 	at picocli.CommandLine.execute(CommandLine.java:2170)
1.066 	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:190)
1.066 	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:127)
1.066 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:95)
1.066 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:88)
1.066 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1.066 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
1.066 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
1.066 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
1.066 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
1.066 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
1.066 Caused by: java.io.UncheckedIOException: java.io.IOException: Failed to create a new filesystem for /opt/keycloak/lib/../providers/apple-identity-provider-1.7.0.jar
1.066 	at io.quarkus.paths.ArchivePathTree.open(ArchivePathTree.java:136)
1.066 	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.<init>(PathTreeClassPathElement.java:47)
1.066 	at io.quarkus.bootstrap.classloading.PathTreeClassPathElement.<init>(PathTreeClassPathElement.java:43)
1.066 	at io.quarkus.bootstrap.classloading.ClassPathElement.fromPath(ClassPathElement.java:83)
1.066 	at io.quarkus.bootstrap.app.CuratedApplication.createDeploymentClassLoader(CuratedApplication.java:334)
1.066 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:174)
1.066 	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
1.066 	... 26 more
1.066 Caused by: java.io.IOException: Failed to create a new filesystem for /opt/keycloak/lib/../providers/apple-identity-provider-1.7.0.jar
1.066 	at io.quarkus.fs.util.ZipUtils.newFileSystem(ZipUtils.java:219)
1.066 	at io.quarkus.fs.util.ZipUtils.newFileSystem(ZipUtils.java:198)
1.066 	at io.quarkus.paths.ArchivePathTree.openFs(ArchivePathTree.java:128)
1.066 	at io.quarkus.paths.ArchivePathTree.open(ArchivePathTree.java:134)
1.066 	... 32 more
1.066 Caused by: java.nio.file.AccessDeniedException: /opt/keycloak/lib/../providers/apple-identity-provider-1.7.0.jar
1.066 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
1.066 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
1.066 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
1.066 	at java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
1.066 	at io.quarkus.fs.util.sysfs.ConfigurableFileSystemProviderWrapper.checkAccess(ConfigurableFileSystemProviderWrapper.java:49)
1.066 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:170)
1.066 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
1.066 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
1.066 	at io.quarkus.fs.util.ZipUtils.newFileSystem(ZipUtils.java:216)
1.067 	... 35 more
------
Dockerfile:26
--------------------
  24 |     
  25 |     # build optimized image
  26 | >>> RUN /opt/keycloak/bin/kc.sh --verbose build 
  27 |     
  28 |     FROM quay.io/keycloak/keycloak:22.0.1
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/keycloak/bin/kc.sh --verbose build" did not complete successfully: exit code: 1
```

Am I doing something wrong? Can someone help me?

**Comment by klausbetz** [comment]
Hi @laurocesar,

Thank you for the detailed error description. 👍   

I'm glad I have some docker Pros in my office 😀   
We were able to replicate this issue and have a fix for you.

In the end we made the jar file executable by adding `--chmod=755` to the `ADD` command in the dockerfile.

See following working example:
```Dockerfile
FROM quay.io/keycloak/keycloak:22.0.1 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
ENV KC_HTTP_RELATIVE_PATH="/auth"

# Install custom providers

# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chmod=755 https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.7.0/apple-identity-provider-1.7.0.jar /opt/keycloak/providers/apple-identity-provider-1.7.0.jar

# build optimized image
RUN /opt/keycloak/bin/kc.sh build 

FROM quay.io/keycloak/keycloak:22.0.1

COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
