### ISSUE TITLE
apple identity provider oauth callback: java.lang.NullPointerException:  identityProviderConfig is null

### ISSUE THREAD

**Issue by meachinecoder123** [klausbetz/apple-identity-provider-keycloak#85]
2024-10-25 05:22:01,162 WARN  [org.keycloak.events] (executor-thread-1) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=b20463ff-ec1e-4958-ae29-b1a3e5f3d27c, clientId=oorvasi, userId=null, ipAddress=111.22.314.034, error=identity_provider_login_failure, idp=apple, code_id=84b2de4f-23e8-42a5-9d1e-b61bd2fe4e54
2024-10-25 05:22:41,912 ERROR [com.ios.keycloak.nativeapps.AppleIdentityProviderEndpoint] (executor-thread-1) Failed to complete apple identity provider oauth callback: java.lang.NullPointerException: Cannot invoke "org.keycloak.models.IdentityProviderModel.getAlias()" because "identityProviderConfig" is null
        at org.keycloak.services.resources.IdentityBrokerService.authenticated(IdentityBrokerService.java:502)
        at com.ios.keycloak.nativeapps.AppleIdentityProviderEndpoint.authResponse(AppleIdentityProviderEndpoint.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:142)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:168)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
 
2024-10-25 05:22:41,915 WARN  [org.keycloak.events] (executor-thread-1) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=b20463ff-ec1e-4958-ae29-b1a3e5f3d27c, clientId=oorvasi, userId=null, ipAddress=111.22.314.034, error=identity_provider_login_failure, idp=apple, code_id=84b2de4f-23e8-42a5-9d1e-b61bd2fe4e54

**Comment by yaseerapure** [comment]
I'm also facing this issue. Has anyone resolved it?

**Comment by therock24** [comment]
This issue happens because you are not using a compatible plugin version for your Keycloak version.
The table is in the README file. After putting a compatible version, I was able to fix this issue.

Keycloak Version | Extension Version
-- | --
< 17.0.0 | Not tested. Use at your own risk.
17.0.0 <= 19.0.3 | 1.2.0
20.0.0 <= 20.0.5 ℹ️ | 1.3.0 <= 1.4.1
21.0.0 <= 21.0.2 ℹ️ | 1.5.0
21.1.0 <= 21.1.2 ℹ️ | 1.6.0
22.0.0 < 23.0.0 | 1.7.0 <= 1.8.0
23.0.0 < 25.0.0 | 1.9.0 <= 1.12.0
>= 25.0.0 | >= 1.13.0

**Comment by romatos** [comment]
I'm facing the same issue. I'm using the library version 1.13.0, and Keycloak is on version 26.0.6.

Error: Unexpected error when authenticating with identity provider

**Comment by klausbetz** [comment]
I just gave it a test using Keycloak `26.0.6` and `1.13.0`. At least for me it worked just fine.  
This is not the answer you wanted to hear, I guess.

@romatos @meachinecoder123 could you please share more details about your environment:
- logs of the whole keycloak startup and apple-logins via this extension
- Do you use docker for Keycloak?
